### ISSUE TITLE
"isAddtionalStep技巧"

### ISSUE THREAD

**Issue by CaledoniaProject** [safe6Sec/CodeqlNote#1]
"isAddtionalStep技巧" 这里说的xsser文章可以加上去吗？

**Comment by safe6Sec** [comment]
> "isAddtionalStep技巧" 这里说的xsser文章可以加上去吗？

粘了啊，仔细看看末尾关于数据流的文章

**Comment by CaledoniaProject** [comment]
找到了 https://xz.aliyun.com/t/8240
